name: buzzify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  supabase_flutter: ^2.2.0
  google_sign_in: ^6.1.6
  just_audio: ^0.9.36
  palette_generator: ^0.3.3+7
  flutter_launcher_icons: ^0.14.4
  http: ^1.5.0
  scrollable_positioned_list: ^0.3.8
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.5
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo-only-logo.png"

flutter:
  uses-material-design: true

  assets:
        - assets/fonts/
        - assets/images/
        - assets/vectors/

  fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Black.ttf
                weight: 900
              - asset: assets/fonts/Roboto-Bold.ttf
                weight: 700
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 500
              - asset: assets/fonts/Roboto-Regular.ttf
                weight: 400
              - asset: assets/fonts/Roboto-Light.ttf
                weight: 300
